name: Pytest CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  pyversion: "3.13"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.pyversion }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.pyversion }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov
      - name: Test with pytest
        run: pytest -v --cov=./ --cov-report term-missing
